# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Use an Ubuntu box compatible with libvirt
  config.vm.box = "bento/ubuntu-24.04"

  # Networking
  config.vm.network "private_network", ip: "192.168.56.14"
  config.vm.network "public_network", dev: "wlp2s0"


  # Provider-specific configuration for Libvirt/QEMU
  config.vm.provider "libvirt" do |lv|
    lv.memory = 1600
    lv.cpus   = 2
    lv.driver = "qemu"   # explicitly use QEMU driver
  end

  # Provisioning
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y apache2
  SHELL
end

