# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Use an Ubuntu box compatible with libvirt
  config.vm.box = "eurolinux-vagrant/centos-stream-9"

  # Networking
  config.vm.network "private_network", ip: "192.168.56.16"
  config.vm.network "public_network", dev: "wlp2s0"


  # Provider-specific configuration for Libvirt/QEMU
  config.vm.provider "libvirt" do |lv|
    lv.memory = 1600
    lv.nic_model_type = "virtio" 
    lv.cpus   = 2
    lv.driver = "qemu"   # explicitly use QEMU driver
  end

  # Provisioning
config.vm.provision "shell", inline: <<-SHELL
       yum install httpd wget unzip vim -y
       systemctl start httpd
       systemctl enabled httpd
       mkdir -p /tmp/finance
       cd /tmp/finance
       wget https://www.tooplate.com/zip-templates/2135_mini_finance.zip
       unzip -o 2135_mini_finance.zip
       cp -r 2135_mini_finance/* /var/www/html/
       systemctl restart httpd
       cd /tmp/
       rm -rf /tmp/finance
     SHELL
  end
 