Vagrant.configure("2") do |config|

  # Base settings
  config.vm.boot_timeout = 600
  config.ssh.username = "vagrant"
  config.ssh.insert_key = false

  # Hostmanager
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true

  # Global libvirt settings
  config.vm.provider :libvirt do |libvirt|
    libvirt.nic_model_type = "virtio"
    libvirt.machine_type   = "pc"
    libvirt.driver         = "qemu"
  end

  ############################
  # DB VM
  ############################
  config.vm.define "db01" do |db01|
    db01.vm.box = "eurolinux-vagrant/centos-stream-9"
    db01.vm.box_version = "9.0.43"
    db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "192.168.121.15"

    db01.vm.provider :libvirt do |libvirt|
      libvirt.memory = 600
      libvirt.cpus   = 1
    end
  end

  ############################
  # Memcache VM
  ############################
  config.vm.define "mc01" do |mc01|
    mc01.vm.box = "eurolinux-vagrant/centos-stream-9"
    mc01.vm.box_version = "9.0.43"
    mc01.vm.hostname = "mc01"
    mc01.vm.network "private_network", ip: "192.168.121.14"

    mc01.vm.provider :libvirt do |libvirt|
      libvirt.memory = 600
      libvirt.cpus   = 1
    end
  end

  ############################
  # RabbitMQ VM
  ############################
  config.vm.define "rmq01" do |rmq01|
    rmq01.vm.box = "eurolinux-vagrant/centos-stream-9"
    rmq01.vm.box_version = "9.0.43"
    rmq01.vm.hostname = "rmq01"
    rmq01.vm.network "private_network", ip: "192.168.121.13"

    rmq01.vm.provider :libvirt do |libvirt|
      libvirt.memory = 600
      libvirt.cpus   = 1
    end
  end

  ############################
  # Tomcat VM
  ############################
  config.vm.define "app01" do |app01|
    app01.vm.box = "eurolinux-vagrant/centos-stream-9"
    app01.vm.box_version = "9.0.43"
    app01.vm.hostname = "app01"
    app01.vm.network "private_network", ip: "192.168.121.12"

    app01.vm.provider :libvirt do |libvirt|
      libvirt.memory = 800
      libvirt.cpus   = 2
    end
  end

  ############################
  # Nginx VM
  ############################
  config.vm.define "web01" do |web01|
    web01.vm.box = "bento/ubuntu-24.04"
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.121.11"

    web01.vm.provider :libvirt do |libvirt|
      libvirt.memory = 800
      libvirt.cpus   = 1
    end
  end

end
